"""LLM-based explanation generator with pluggable backends.

This module used to hard-require the Anthropic SDK and an API key. As of
v2.3 it supports three backends (see :mod:`ai.backends`):

1. ``deterministic`` — no LLM, rule-based, always works offline.
2. ``ollama`` — local HTTP LLM; traces never leave the host.
3. ``anthropic`` — Claude API; opt-in only.

The public API (``Explainer``, ``Explanation``, ``ExplanationConfig``) is
preserved for backward compatibility.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, List
import os

from .prompts import (
    SYSTEM_PROMPT,
    EXPLANATION_PROMPT,
    EXECUTIVE_SUMMARY_PROMPT,
    COMPARISON_PROMPT,
)
from .pattern_detector import PatternDetectionResult
from .fact_extractor import FactSet
from .backends import Backend, BackendResponse, BackendUnavailable, make_backend


@dataclass
class ExplanationConfig:
    """Configuration for explanation generation.

    ``backend`` selects the generator; default ``auto`` resolves to
    deterministic (safe default — no network egress).
    """
    backend: str = "auto"
    model: str = "claude-sonnet-4-20250514"  # only used by anthropic backend
    ollama_model: str = "llama3.1:8b"
    ollama_host: str = "http://localhost:11434"
    max_tokens: int = 1024
    temperature: float = 0.3
    clock_period_ns: float = 10.0
    rate_max_tokens: int = 100
    rate_refill_rate: int = 10
    pos_max_long: int = 10000
    pos_max_short: int = 10000


@dataclass
class Explanation:
    """Structured explanation produced by any backend."""
    summary: str
    key_findings: List[str]
    root_cause: Optional[str]
    recommendations: List[str]
    raw_response: str
    backend: str = "unknown"
    model: Optional[str] = None
    offline: bool = True

    def to_dict(self) -> dict:
        return {
            'summary': self.summary,
            'key_findings': self.key_findings,
            'root_cause': self.root_cause,
            'recommendations': self.recommendations,
            'backend': self.backend,
            'model': self.model,
            'offline': self.offline,
        }

    def to_markdown(self) -> str:
        lines = ["## Analysis Summary", "", self.summary, "", "## Key Findings", ""]
        for finding in self.key_findings:
            lines.append(f"- {finding}")

        if self.root_cause:
            lines.extend(["", "## Root Cause Analysis", "", self.root_cause])

        if self.recommendations:
            lines.extend(["", "## Recommendations", ""])
            for rec in self.recommendations:
                lines.append(f"- {rec}")

        lines.extend([
            "",
            "---",
            f"_Generated by `{self.backend}` backend"
            + (f" (model: `{self.model}`)" if self.model else "")
            + (" — offline_" if self.offline else " — network call_"),
        ])
        return "\n".join(lines)


class Explainer:
    """Generate natural-language explanations from trace analysis.

    Supports three backends via ``ExplanationConfig.backend``:
    ``auto`` / ``deterministic`` (default, offline, no LLM),
    ``ollama`` (local LLM), ``anthropic`` (Claude API, opt-in).

    The legacy ``api_key`` constructor argument is preserved for
    backward compatibility but is only honoured by the anthropic
    backend. It no longer raises when absent — the default backend
    does not need it.
    """

    def __init__(self, config: Optional[ExplanationConfig] = None,
                 api_key: Optional[str] = None,
                 backend: Optional[Backend] = None):
        self.config = config or ExplanationConfig()
        self._api_key = api_key or os.environ.get('ANTHROPIC_API_KEY')

        if backend is not None:
            self._backend = backend
        else:
            # Resolve the backend lazily so construction doesn't fail
            # in tests / offline environments.
            self._backend = self._resolve_backend()

    # -- public API ---------------------------------------------------

    def explain(self, facts: FactSet,
                patterns: Optional[PatternDetectionResult] = None) -> Explanation:
        """Generate a structured explanation from facts and patterns."""
        prompt = EXPLANATION_PROMPT.format(
            facts=facts.to_llm_context(),
            clock_period_ns=self.config.clock_period_ns,
            rate_max_tokens=self.config.rate_max_tokens,
            rate_refill_rate=self.config.rate_refill_rate,
            pos_max_long=self.config.pos_max_long,
            pos_max_short=self.config.pos_max_short,
        )
        resp = self._call(prompt)
        return self._parse_explanation(resp)

    def executive_summary(self, facts: FactSet) -> str:
        prompt = EXECUTIVE_SUMMARY_PROMPT.format(facts=facts.to_llm_context())
        return self._call(prompt).text

    def compare_runs(self, baseline: FactSet, candidate: FactSet) -> str:
        prompt = COMPARISON_PROMPT.format(
            baseline_facts=baseline.to_llm_context(),
            candidate_facts=candidate.to_llm_context(),
        )
        return self._call(prompt).text

    @property
    def backend_name(self) -> str:
        return self._backend.name

    @property
    def offline(self) -> bool:
        return self._backend.offline

    # -- internals ----------------------------------------------------

    def _resolve_backend(self) -> Backend:
        try:
            return make_backend(
                self.config.backend,
                ollama_model=self.config.ollama_model,
                ollama_host=self.config.ollama_host,
                anthropic_model=self.config.model,
                anthropic_api_key=self._api_key,
            )
        except BackendUnavailable:
            # Fall back to deterministic rather than raising. The caller
            # can still inspect ``backend_name`` to see what they got.
            from .backends import DeterministicBackend
            return DeterministicBackend()

    def _call(self, prompt: str) -> BackendResponse:
        try:
            return self._backend.generate(
                system=SYSTEM_PROMPT,
                prompt=prompt,
                max_tokens=self.config.max_tokens,
                temperature=self.config.temperature,
            )
        except BackendUnavailable as e:
            # Backend became unavailable at call time — fall back safely.
            from .backends import DeterministicBackend
            fallback = DeterministicBackend()
            resp = fallback.generate(
                system=SYSTEM_PROMPT, prompt=prompt,
                max_tokens=self.config.max_tokens,
                temperature=self.config.temperature,
            )
            resp.text = f"[backend fallback: {e}]\n\n" + resp.text
            return resp
        except Exception as e:  # pragma: no cover — defensive
            return BackendResponse(
                text=f"Error calling backend: {e}",
                backend=self._backend.name,
                model=None,
                offline=True,
            )

    def _parse_explanation(self, resp: BackendResponse) -> Explanation:
        response = resp.text
        summary = ""
        key_findings: List[str] = []
        root_cause: Optional[str] = None
        recommendations: List[str] = []
        current_section: Optional[str] = None

        for line in response.split('\n'):
            line = line.strip()
            upper = line.upper()

            if 'SUMMARY' in upper and len(line) < 40:
                current_section = 'summary'
                continue
            if ('KEY FINDINGS' in upper or upper.startswith('FINDINGS')) and len(line) < 40:
                current_section = 'findings'
                continue
            if 'ROOT CAUSE' in upper and len(line) < 40:
                current_section = 'root_cause'
                continue
            if 'RECOMMENDATION' in upper and len(line) < 40:
                current_section = 'recommendations'
                continue

            if not line:
                continue

            if current_section == 'summary':
                summary += line + " "
            elif current_section == 'findings':
                if line.startswith(('- ', '* ', '1.', '2.', '3.', '4.', '5.')):
                    key_findings.append(line.lstrip('-*0123456789. ').strip())
            elif current_section == 'root_cause':
                root_cause = (root_cause or "") + line + " "
            elif current_section == 'recommendations':
                if line.startswith(('- ', '* ', '1.', '2.', '3.', '4.', '5.')):
                    recommendations.append(line.lstrip('-*0123456789. ').strip())

        return Explanation(
            summary=summary.strip(),
            key_findings=key_findings,
            root_cause=root_cause.strip() if root_cause else None,
            recommendations=recommendations,
            raw_response=response,
            backend=resp.backend,
            model=resp.model,
            offline=resp.offline,
        )
